import type { CaseStudy } from './cases.ts';
import type { Profile, Project, Skills, Status } from './content.ts';
import { esc } from './svg.ts';

// Each image is one link per theme, hidden by GitHub's CSS for `#gh-dark-mode-only` and
// `#gh-light-mode-only` hrefs, so it follows the viewer's GitHub theme. Width variants are
// <picture> sources with width-only queries: for a viewer with an explicit theme, GitHub's
// <themed-picture> rewrites any prefers-color-scheme query and drops a width beside it. A mailto:
// cannot carry the fragment, so the e-mail button alone uses prefers-color-scheme, and the OS theme.

const STATUS_TEXT: Record<Status, string> = {
  live: 'live',
  'in-use': 'in use',
  developed: 'developed',
  active: 'active',
  'in-development': 'in development',
};

// The bot commits the drawings to the output branch, so main's history and contributors stay the owner's.
export const ASSETS = 'https://raw.githubusercontent.com/ErtugrulTurkmen/ErtugrulTurkmen/output/assets/';

// Phone drawings show where GitHub's README column is 520px or narrower: below a 600px viewport,
// and from 768px to 890px, where the profile sidebar moves beside the README.
const PHONE = '(max-width: 600px), (min-width: 768px) and (max-width: 890px)';
// Below 1280px the column is narrower than 846px, too narrow for two cards side by side.
const NOT_FULL = '(max-width: 1279px)';

const src = (name: string, mode: 'dark' | 'light', variant = '') => `${ASSETS}${name}${variant}-${mode}.svg`;

/** `mobile`: has a phone variant. `wide`: has a full-width variant for columns too narrow for two cards. */
function pic(name: string, alt: string, { mobile = false, wide = false, href = '' } = {}): string {
  return (['dark', 'light'] as const)
    .map((mode) => {
      const img = `<img alt="${esc(alt)}" src="${src(name, mode)}">`;
      const sources = [mobile && [PHONE, '-mobile'], wide && [NOT_FULL, '-wide']]
        .filter((x): x is [string, string] => Boolean(x))
        .map(([media, variant]) => `<source media="${media}" srcset="${src(name, mode, variant)}">`)
        .join('');
      return `<a href="${esc(href)}#gh-${mode}-mode-only">${sources ? `<picture>${sources}${img}</picture>` : img}</a>`;
    })
    .join('');
}

const button = (href: string, name: string, alt: string): string =>
  href.startsWith('mailto:')
    ? `<a href="${esc(href)}"><picture><source media="(prefers-color-scheme: light)" srcset="${src(name, 'light')}"><img alt="${esc(alt)}" src="${src(name, 'dark')}"></picture></a>`
    : pic(name, alt, { href });

// Alt text holds no live numbers: README.md changes only on a rebuild, the drawings every 6 hours.
export const heroAlt = (p: Profile): string =>
  `${p.name}. ${p.eyebrow}. ${p.tagline} Focus: ${p.focus.join(', ')}. ` +
  `${p.now.map((n) => `${n.label}: ${n.text}`).join('. ')}. ` +
  'With contributions over the last 12 months, commits in my own repositories, repository count and main language, private work included.';

export const cardAlt = (pr: Project): string =>
  `${pr.name} (${STATUS_TEXT[pr.status]}, ${pr.visibility.replace('-', ' ')} source): ${pr.kind}. ${pr.summary} ` +
  `${pr.highlights.join('. ')}. Stack: ${pr.stack.join(', ')}.`;

export const skillsAlt = (s: Skills): string =>
  `Currently learning: ${s.learning.join(', ')}. ` +
  [...s.groups, s.practices].map((g) => `${g.title}: ${g.items.join(', ')}`).join('. ') + '.';

export const aboutAlt = (p: Profile): string =>
  `${p.about.lede} ${p.about.paragraphs.join(' ')} ` + p.about.principles.map(([head, body]) => `${head}: ${body}`).join(' ');

export const titleAlt = (p: Profile): string =>
  `Drawn by ${p.name}. Checked by GitHub Actions every 6 hours, with the date of the last revision. ` +
  'Numbers and drawings are regenerated from live GitHub data; private work is counted, never named.';

// Images in one paragraph share one line, since GitHub's renderers disagree on whether a newline
// there is a space or a <br>. Paragraphs are centred: a 320px phone drawing never grows to fill a
// wider column.
export function readme(p: Profile, projects: Project[], skills: Skills): string {
  const [feature, ...rest] = projects;
  const rows: string[] = [];
  for (let i = 0; i < rest.length; i += 2) {
    // No space between the pair: its gutter is drawn inside the two images.
    rows.push(rest.slice(i, i + 2).map((pr) => pic(`card-${pr.slug}`, cardAlt(pr), { mobile: true, wide: true, href: pr.href })).join(''));
  }
  return `<!-- Generated by src/build.ts from src/content.ts. Edit that, then run: npm run build -->

<p align="center">${pic('hero', heroAlt(p), { mobile: true })}</p>

<p align="center">${pic('h-about', 'About', { mobile: true })}</p>

<p align="center">${pic('about', aboutAlt(p), { mobile: true })}</p>

<p align="center">${pic('h-work', 'Selected work', { mobile: true })}</p>

<p align="center">${pic(`card-${feature.slug}`, cardAlt(feature), { mobile: true, href: `projects/${feature.slug}.md` })}</p>

${button(feature.href, `btn-${feature.slug}`, `${feature.name} on the App Store`)} ${button(`projects/${feature.slug}.md`, 'btn-case', `${feature.name} case study`)}

${rows.map((row) => `<p align="center">${row}</p>`).join('\n\n')}

<p align="center">${pic('h-skills', 'Skills', { mobile: true })}</p>

<p align="center">${pic('skills', skillsAlt(skills), { mobile: true })}</p>

<p align="center">${pic('h-activity', 'Activity', { mobile: true })}</p>

<p align="center">${pic('calendar', '3D contribution calendar of the last 12 months, private work included, with the busiest day marked.', { mobile: true })}</p>

<p align="center">${pic('h-contact', 'Contact', { mobile: true })}</p>

${button(p.linkedin, 'btn-linkedin', 'LinkedIn')} ${button(`mailto:${p.email}`, 'btn-email', `Email ${p.email}`)}

<p align="center">${pic('titleblock', titleAlt(p), { mobile: true })}</p>
`;
}

const list = (items: string[]) => items.map((i) => `- ${i}`).join('\n');

const SOURCE_NOTE: Record<Project['visibility'], string> = {
  private: 'the source is described, never shown.',
  'soon-public': 'the source will be public.',
  public: 'the source is public.',
};

export function caseStudy(pr: Project, n: number, c: CaseStudy): string {
  const links = c.links?.map(([label, href]) => `[${label}](${href})`).join(' · ');
  return `<!-- Generated by src/build.ts from src/cases.ts and src/content.ts. Edit those, then run: npm run build -->

<p align="center">${pic(`case-${pr.slug}`, `${pr.name}: ${pr.caption}. ${pr.kind}. Stack: ${pr.stack.join(', ')}.`, { mobile: true })}</p>

> ${pr.summary}

## Problem

${c.problem}

## What I built

${list(c.built)}

## Security and privacy

${list(c.security)}

## Engineering

${list(c.engineering)}

## Status

${c.status}${links ? `\n\n${links}` : ''}

---

<sub>Sheet ${String(n + 1).padStart(2, '0')} of the drawing set on [my profile](https://github.com/ErtugrulTurkmen) · ${SOURCE_NOTE[pr.visibility]}</sub>
`;
}
