import type { CaseStudy } from './cases.ts';
import type { Profile, Project, Skills, Status } from './content.ts';
import { esc } from './svg.ts';

// Alt text carries everything each SVG says. Three ways an image gets onto the page:
// - pic():    unlinked <picture>. Dark is default and fallback; light and phone variants by media query.
// - linked(): a clickable image. GitHub pulls <img> out of a <picture> nested in <a> (checked with
//             its Markdown API, 2026-09-30), so each theme gets its own <a>, hidden by GitHub's CSS
//             rule `.readme [href$="#gh-light-mode-only"]{display:none}` and its dark twin.
// - button(): one image that reads on both themes, for mailto: where a fragment is unsafe.

const STATUS_TEXT: Record<Status, string> = {
  live: 'live',
  'in-use': 'in use',
  developed: 'developed',
  active: 'active',
  'in-development': 'in development',
};

/**
 * Generated drawings live on the `output` branch, written there by the workflow as github-actions[bot].
 * Keeping them off main keeps main's history, and the repository's contributor list, to the owner alone.
 */
export const ASSETS = 'https://raw.githubusercontent.com/ErtugrulTurkmen/ErtugrulTurkmen/output/assets/';

const src = (name: string, mode: 'dark' | 'light', mobile = false, base = ASSETS) => `${base}${name}${mobile ? '-mobile' : ''}-${mode}.svg`;

/** `mobile`: the asset also has a phone-width variant. */
export function pic(name: string, alt: string, mobile = false, base = ASSETS): string {
  const sources = [
    mobile && `<source media="(max-width: 600px) and (prefers-color-scheme: light)" srcset="${src(name, 'light', true, base)}">`,
    mobile && `<source media="(max-width: 600px)" srcset="${src(name, 'dark', true, base)}">`,
    `<source media="(prefers-color-scheme: light)" srcset="${src(name, 'light', false, base)}">`,
  ].filter(Boolean);
  return `<picture>${sources.join('')}<img alt="${esc(alt)}" src="${src(name, 'dark', false, base)}"></picture>`;
}

export const linked = (href: string, name: string, alt: string): string =>
  (['dark', 'light'] as const)
    .map((mode) => `<a href="${href}#gh-${mode}-mode-only"><img alt="${esc(alt)}" src="${src(name, mode)}"></a>`)
    .join('');

const button = (href: string, name: string, alt: string): string =>
  `<a href="${href}"><img alt="${esc(alt)}" src="${ASSETS}${name}.svg"></a>`;

// README.md on main changes only when its owner rebuilds it, while the drawings refresh every
// 6 hours, so alt text carries no live numbers that would go stale between the two.
export const heroAlt = (p: Profile): string =>
  `${p.name}. ${p.eyebrow}. ${p.tagline} Focus: ${p.focus.join(', ')}. ` +
  `${p.now.map((n) => `${n.label}: ${n.text}`).join('. ')}. ` +
  'With contributions, commits, repositories and main language over the last 12 months, private work included.';

export const cardAlt = (pr: Project): string =>
  `${pr.name} (${STATUS_TEXT[pr.status]}, ${pr.visibility.replace('-', ' ')} source): ${pr.kind}. ${pr.summary} ` +
  `${pr.highlights.join('. ')}. Stack: ${pr.stack.join(', ')}.`;

export const skillsAlt = (s: Skills): string =>
  `Currently learning: ${s.learning.join(', ')}. ` +
  [...s.groups, s.practices].map((g) => `${g.title}: ${g.items.join(', ')}`).join('. ') + '.';

export const aboutAlt = (p: Profile): string =>
  `${p.about.quote} ${p.about.intro} ` + p.about.principles.map(([head, body]) => `${head}: ${body}`).join(' ');

export const titleAlt = (p: Profile): string =>
  `Drawn by ${p.name}. Checked by GitHub Actions every 6 hours, with the date of the last revision. ` +
  'Numbers and drawings are regenerated from live GitHub data; private work is counted, never named.';

export function readme(p: Profile, projects: Project[], skills: Skills): string {
  const [feature, ...rest] = projects;
  const rows: string[] = [];
  for (let i = 0; i < rest.length; i += 2) {
    rows.push(rest.slice(i, i + 2).map((pr) => linked(pr.href, `card-${pr.slug}`, cardAlt(pr))).join('\n'));
  }
  return `<!-- Generated by src/build.ts from src/content.ts and data/. Edit those, then run: npm run build -->

${pic('hero', heroAlt(p), true)}

${pic('h-about', 'About', true)}

${pic('about', aboutAlt(p), true)}

${pic('h-work', 'Selected work', true)}

${pic(`card-${feature.slug}`, cardAlt(feature), true)}

${button(feature.href, `btn-${feature.slug}`, `${feature.name} on the App Store`)}
${button(`projects/${feature.slug}.md`, 'btn-case', `${feature.name} case study`)}

${rows.join('\n\n')}

${pic('h-skills', 'Skills', true)}

${pic('skills', skillsAlt(skills), true)}

${pic('h-activity', 'Activity', true)}

${pic('calendar', '3D contribution calendar of the last 12 months, private work included.')}

${pic('h-contact', 'Contact', true)}

${button(p.linkedin, 'btn-linkedin', 'LinkedIn')}
${button(`mailto:${p.email}`, 'btn-email', `Email ${p.email}`)}

${pic('titleblock', titleAlt(p), true)}
`;
}

const list = (items: string[]) => items.map((i) => `- ${i}`).join('\n');

/** A project's case-study page, projects/<slug>.md. */
export function caseStudy(pr: Project, n: number, c: CaseStudy): string {
  const links = c.links?.map(([label, href]) => `[${label}](${href})`).join(' · ');
  return `<!-- Generated by src/build.ts from src/cases.ts. Edit that, then run: npm run build -->

${pic(`case-${pr.slug}`, `${pr.name}: ${pr.caption}. ${pr.kind}. Stack: ${pr.stack.join(', ')}.`, true)}

> ${pr.summary}

## Problem

${c.problem}

## What I built

${list(c.built)}

## Security and privacy

${list(c.security)}

## Engineering

${list(c.engineering)}

## Status

${c.status}${links ? `\n\n${links}` : ''}

---

<sub>Sheet 0${n + 1} of the drawing set on [my profile](https://github.com/ErtugrulTurkmen) · the source is described, never shown.</sub>
`;
}
